name: Import standard labels

on:
   workflow_dispatch:
jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: j-dogcoder/gh-action-labels@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: 'j-dogcoder'
        repository-name: 'gh-action-labels'
        force: true
